=== manabuishii/jgaworkflowspecchecker/cmd/configfile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "workflow_file": {
        "$id": "#workflow_file",
        "description": "CWL Workflow File",
        "type": "object",
        "properties": {
          "path": {
            "description": "CWL Workflow file path",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "output_directory": {
        "$id": "#output_directory",
        "description": "Output top directory path, all sample id directory creates under this directory",
        "type": "object",
        "properties": {
          "path": {
            "description": "Output top directory path",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "container_cache_directory": {
        "$id": "#container_cache_directory",
        "description": "Container image cache directory path, singularity or docker images are save this directory",
        "type": "object",
        "properties": {
          "path": {
            "description": "Container image cache directory",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "reference":{
        "$id": "#reference",
        "description": "Reference",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of reference",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "sortsam_max_records_in_ram": {
        "description": "",
        "type": "integer"
      },
      "sortsam_java_options": {
        "description": "",
        "type": "string"
      },
      "cores": {
        "description": "",
        "type": "integer"
      },
      "bwa_bases_per_batch": {
        "description": "",
        "type": "integer"
      },
      "use_bqsr": {
        "description": "",
        "type": "boolean"
      },
      "dbsnp":{
        "$id": "#dbsnp",
        "description": "dbsnp",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of dbsnp",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "mills":{
        "$id": "#mills",
        "description": "mills",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of mills",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "known_indels":{
        "$id": "#known_indels",
        "description": "known_indels",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of known_indels",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_autosome_PAR_interval_bed":{
        "$id": "#haplotypecaller_autosome_PAR_interval_bed",
        "description": "haplotypecaller_autosome_PAR_interval_bed autosome_PAR and ploidy 2",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_autosome_PAR_interval_bed",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_autosome_PAR_interval_list":{
        "$id": "#haplotypecaller_autosome_PAR_interval_list",
        "description": "haplotypecaller_autosome_PAR_interval_list autosome_PAR and ploidy 2",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_autosome_PAR_interval_list",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_chrX_nonPAR_interval_bed":{
        "$id": "#haplotypecaller_chrX_nonPAR_interval_bed",
        "description": "haplotypecaller_chrX_nonPAR_interval_bed",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_chrX_nonPAR_interval_bed chrX_nonPAR ploidy 1 and ploidy 2",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_chrX_nonPAR_interval_list":{
        "$id": "#haplotypecaller_chrX_nonPAR_interval_list",
        "description": "haplotypecaller_chrX_nonPAR_interval_list",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_chrX_nonPAR_interval_list chrX_nonPAR ploidy 1 and ploidy 2",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_chrY_nonPAR_interval_bed":{
        "$id": "#haplotypecaller_chrY_nonPAR_interval_bed",
        "description": "haplotypecaller_chrY_nonPAR_interval_bed ploidy 1",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_chrY_nonPAR_interval_bed",
            "type": "string"
          }
        },
        "required": [ "path" ]
      },
      "haplotypecaller_chrY_nonPAR_interval_list":{
        "$id": "#haplotypecaller_chrY_nonPAR_interval_list",
        "description": "haplotypecaller_chrY_nonPAR_interval_list ploidy 1",
        "type": "object",
        "properties": {
          "path": {
            "description": "File path of haplotypecaller_chrY_nonPAR_interval_list",
            "type": "string"
          }
        },
        "required": [ "path" ]
      }
  },

  "required": [
      "workflow_file",
      "output_directory",
      "container_cache_directory",
      "reference",
      "sortsam_max_records_in_ram",
      "sortsam_java_options",
      "cores",
      "bwa_bases_per_batch",
      "use_bqsr",
      "dbsnp",
      "mills",
      "known_indels",
      "haplotypecaller_autosome_PAR_interval_bed",
      "haplotypecaller_autosome_PAR_interval_list",
      "haplotypecaller_chrX_nonPAR_interval_bed",
      "haplotypecaller_chrX_nonPAR_interval_list",
      "haplotypecaller_chrY_nonPAR_interval_bed",
      "haplotypecaller_chrY_nonPAR_interval_list"
  ]
}

=== manabuishii/jgaworkflowspecchecker/test/datafiles/configfile_1run-test.json
{
    "workflow_file": {
        "path": "../test/workflowfiles/dummyworkflow.cwl"
    },
    "output_directory": {
        "path": "../tmp/dummydata"
    },
    "container_cache_directory": {
        "path": "../tmp/dummycachedir"
    },
    "reference": {
        "path": "../test/secondaryfile/case1.fasta"
    },
    "sortsam_max_records_in_ram": 5000000,
    "sortsam_java_options": "-XX:-UseContainerSupport -Xmx30g",
    "cores": 16,
    "bwa_bases_per_batch": 10000000,
    "use_bqsr": false,
    "dbsnp": {
        "path": "../test/referencefiles/dummy.dbsnp.vcf"
    },
    "mills": {
        "path": "../test/referencefiles/dummy.mills.vcf.gz"
    },
    "known_indels": {
        "path": "../test/referencefiles/dummy.known_indels.vcf.gz"
    },
    "haplotypecaller_autosome_PAR_interval_bed":{
        "path": "../test/referencefiles/dummy.autosome-PAR.bed"
    },
    "haplotypecaller_autosome_PAR_interval_list":{
        "path": "../test/referencefiles/dummy.autosome-PAR.interval_list"
    },
    "haplotypecaller_chrX_nonPAR_interval_bed":{
        "path": "../test/referencefiles/dummy.chrX-nonPAR.bed"
    },
    "haplotypecaller_chrX_nonPAR_interval_list":{
        "path": "../test/referencefiles/dummy.chrX-nonPAR.interval_list"
    },
    "haplotypecaller_chrY_nonPAR_interval_bed":{
        "path": "../test/referencefiles/dummy.chrY-nonPAR.bed"
    },
    "haplotypecaller_chrY_nonPAR_interval_list":{
        "path": "../test/referencefiles/dummy.chrY-nonPAR.interval_list"
    }

}
